### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by NULLlnull** [Darknights-master/Darknights-server#22]
网络异常，登录失败，请稍后重试。错误号10020

**Comment by NULLlnull** [comment]
代理那边没有问题，证书也信任了。全局代理的情况下可以正常访问网页

**Comment by misaka10843** [comment]
可能是明日方舟更改了登录方式（因为很有可能已经发现了这个仓库后更改的）

**Comment by Darknights-master** [comment]
Auth server has been updated.
However, you need some tricks to redirect requests to the Darknights server.
