### ISSUE TITLE
运行main.py出现问题

### ISSUE THREAD

**Issue by jinghuashang** [Darknights-master/Darknights-server#24]
[2022-08-18 14:10:40][localhost][INFO] Connecting to database.
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\Darknights-server-nginx-ver\main.py", line 10, in <module>
    from core import *
  File "C:\Users\****\Desktop\Darknights-server-nginx-ver\core\auth.py", line 9, in <module>
    from utils import logger, api, err, encryption
  File "C:\Users\******\Desktop\Darknights-server-nginx-ver\utils\encryption.py", line 11, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by Darknights-master** [comment]
It is recommended to use conda/miniconda and run `conda install  pycryptodome`.
Note that if you are using Windows, you may rename package folder from 'crypto' to 'Crypto'.

However, you can just try this. 
Delete existing 'Crypto' related packages and run `pip install pycryptodome crypto pycrypto`
But this may fail due to missing some files required by the compiler.

**Comment by AZthemute** [comment]
> But this may fail due to missing some files required by the compiler.

I'm getting this issue, what do I need to do to install this module?

**Comment by jinghuashang** [comment]
> > 但是，由于缺少编译器所需的某些文件，这可能会失败。
> 
> 我遇到了这个问题，我需要做什么来安装这个模块？

我这个问题倒是解决了，好像是少安装了一个模块，pip install pycryptodome ,你试试安装这个模块

**Comment by jinghuashang** [comment]
> > 但是，由于缺少编译器所需的某些文件，这可能会失败。
> 
> 我遇到了这个问题，我需要做什么来安装这个模块？

我这个问题倒是解决了，好像是少安装了一个模块，pip install pycryptodome ,你试试安装这个模块

**Comment by AZthemute** [comment]
Thank you, this worked well.

For others with the same issue:

>run `pip install pycryptodome crypto pycrypto`

this is wrong, just do `pip install pycryptodome`

**Comment by jinghuashang** [comment]
> Thank you, this worked well.
> 
> For others with the same issue:
> 
> >run `pip install pycryptodome crypto pycrypto`
> 
> this is wrong, just do `pip install pycryptodome`

不用谢，不过你的代理脚本能否运行，我的貌似出了点问题

**Comment by Darknights-master** [comment]
Issues regarding 'proxy' will be discussed later.
