### ISSUE TITLE
connection terminated by server

### ISSUE THREAD

**Issue by NstzJC** [Darknights-master/Darknights-server#27]
I can see the flows in mitmproxy,but when launching games, it shows that "网络配置解析失败，请重试" 
at the same time, the script log shows: 
```
connection terminated by server: error code: 0, last stream id: 1, additional data: None
clientconnected
clientdisconnected
```
When I'm checking information in mitmproxy,I find the server didn't respond any GET messages,how can I solve it?

**Comment by s0duku** [comment]
> I can see the flows in mitmproxy,but when launching games, it shows that "网络配置解析失败，请重试" at the same time, the script log shows:
> 
> ```
> connection terminated by server: error code: 0, last stream id: 1, additional data: None
> clientconnected
> clientdisconnected
> ```
> 
> When I'm checking information in mitmproxy,I find the server didn't respond any GET messages,how can I solve it?

I am doing some arknights crack, and I assmue that current aknights client has the server certificate authentication. I found that there are lots of projects on github using the mitmproxy to hijack the response flow, just curious, are these project still can work now?  I think without some client patch or runtime hook technique, system proxy may not able to use.

**Comment by hyouv** [comment]
Yes for CN version.

**Comment by hyouv** [comment]
> > I can see the flows in mitmproxy,but when launching games, it shows that "网络配置解析失败，请重试" at the same time, the script log shows:
> > ```
> > connection terminated by server: error code: 0, last stream id: 1, additional data: None
> > clientconnected
> > clientdisconnected
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I'm checking information in mitmproxy,I find the server didn't respond any GET messages,how can I solve it?
> 
> I am doing some arknights crack, and I assmue that current aknights client has the server certificate authentication. I found that there are lots of projects on github using the mitmproxy to hijack the response flow, just curious, are these project still can work now? I think without some client patch or runtime hook technique, system proxy may not able to use.

Yes for CN version.

**Comment by NstzJC** [comment]
你好，如果你看到这封邮件，代表你的邮件成功发送到了我的邮箱，请等待回复。
